#!/usr/bin/env node

const { exec } = require('@sifrr/dev');

(async function() {
  const exists = await require('@sifrr/dev').checkTag();
  if (exists) return;
  await require('@sifrr/dev').gitAddCommitPush({
    preCommand: 'sh ./scripts/changelog',
    files: ['*CHANGELOG.md'],
    commitMsg: 'chore: update changelog'
  });
  await require('@sifrr/dev').releaseTag();
  await exec(`npm publish --access=public`);
})();

